# Generated by Django 3.2.9 on 2022-01-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
